from typing import Protocol

from backend.app.domain.models.agent_runtime import AgentCheckpoint, AgentSession, TurnJournalEntry


class AgentRuntimeRepository(Protocol):
    def list_agent_sessions(self, session_id: str) -> list[AgentSession]: ...

    def get_agent_session(self, agent_session_id: str) -> AgentSession | None: ...

    def get_agent_session_by_runtime_key(self, session_id: str, runtime_key: str) -> AgentSession | None: ...

    def upsert_agent_session(self, session: AgentSession) -> AgentSession: ...

    def delete_agent_session(self, agent_session_id: str) -> None: ...

    def list_checkpoints(self, agent_session_id: str, limit: int = 10) -> list[AgentCheckpoint]: ...

    def get_latest_checkpoint(self, agent_session_id: str) -> AgentCheckpoint | None: ...

    def append_checkpoint(self, checkpoint: AgentCheckpoint) -> AgentCheckpoint: ...

    def list_turn_journal(self, session_id: str, turn_index: int | None = None) -> list[TurnJournalEntry]: ...

    def get_latest_turn_index(self, session_id: str) -> int: ...

    def append_turn_journal(self, entry: TurnJournalEntry) -> TurnJournalEntry: ...
