from typing import Protocol

from backend.app.domain.models.character import CharacterDefinition
from backend.app.domain.models.model_config import ModelConfig
from backend.app.domain.models.plugin import PluginDefinition
from backend.app.domain.models.settings import AppSettingsSnapshot
from backend.app.domain.models.world import WorldDefinition


class CatalogRepository(Protocol):
    def list_worlds(self) -> list[WorldDefinition]: ...

    def get_world(self, world_id: str) -> WorldDefinition | None: ...

    def create_world(self, world: WorldDefinition) -> WorldDefinition: ...

    def update_world(self, world_id: str, world: WorldDefinition) -> WorldDefinition | None: ...

    def duplicate_world(self, world_id: str) -> WorldDefinition | None: ...

    def list_characters(self) -> list[CharacterDefinition]: ...

    def list_characters_for_world(self, world_id: str) -> list[CharacterDefinition]: ...

    def get_character(self, character_id: str) -> CharacterDefinition | None: ...

    def create_character(self, character: CharacterDefinition) -> CharacterDefinition: ...

    def update_character(self, character_id: str, character: CharacterDefinition) -> CharacterDefinition | None: ...

    def delete_world(self, world_id: str) -> bool: ...

    def delete_all_worlds(self) -> int: ...

    def delete_character(self, character_id: str) -> bool: ...

    def get_settings(self) -> AppSettingsSnapshot: ...

    def update_settings(self, settings: AppSettingsSnapshot) -> AppSettingsSnapshot: ...

    def list_plugins(self) -> list[PluginDefinition]: ...

    def list_models(self) -> list[ModelConfig]: ...

    def get_model(self, model_id: str) -> ModelConfig | None: ...

    def create_model(self, model: ModelConfig) -> ModelConfig: ...

    def update_model(self, model_id: str, model: ModelConfig) -> ModelConfig | None: ...

    def delete_model(self, model_id: str) -> bool: ...

    def set_default_model(self, model_id: str, model_type: str) -> None: ...
