from typing import Protocol

from backend.app.domain.models.rule import RuleDefinition


class RuleRepository(Protocol):
    def list_rules(self, scope: str | None = None) -> list[RuleDefinition]: ...

    def get_rule(self, rule_id: str) -> RuleDefinition | None: ...

    def create_rule(self, rule: RuleDefinition) -> RuleDefinition: ...

    def update_rule(self, rule_id: str, rule: RuleDefinition) -> RuleDefinition | None: ...
