<#
.SYNOPSIS
    同步应用版本号到各构建配置。
.DESCRIPTION
    把指定版本号写入 src-tauri\tauri.conf.json、src-tauri\Cargo.toml 和 package.json；
    若 Android 工程已初始化，同时更新 src-tauri\gen\android\app\tauri.properties
    （versionName 为该版本，versionCode 按 major*1000000+minor*1000+patch 推导，
    与 Tauri CLI 的生成规则一致）。
    文件读写使用显式 UTF-8 无 BOM 编码，避免破坏中文内容。
.PARAMETER Version
    版本号，格式：主.次.修订，例如 0.2.0（不支持预发布后缀）。
.PARAMETER RepoRoot
    仓库根目录，默认取本脚本上一级目录。
.EXAMPLE
    .\scripts\sync-app-version.ps1 -Version 0.2.0
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$Version,
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$ErrorActionPreference = "Stop"

if ($Version -notmatch '^\d+\.\d+\.\d+$') {
    throw "Invalid version format: '$Version'. Expected MAJOR.MINOR.PATCH, e.g. 0.2.0"
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

$targets = @(
    @{ Path = (Join-Path $RepoRoot "src-tauri\tauri.conf.json"); Pattern = '"version":\s*"[^"]*"'; Replacement = '"version": "{0}"' }
    @{ Path = (Join-Path $RepoRoot "package.json");              Pattern = '"version":\s*"[^"]*"'; Replacement = '"version": "{0}"' }
    @{ Path = (Join-Path $RepoRoot "src-tauri\Cargo.toml");      Pattern = '(?m)^version = "[^"]*"'; Replacement = 'version = "{0}"' }
)

foreach ($t in $targets) {
    $re = [regex]::new($t.Pattern)
    $content = [System.IO.File]::ReadAllText($t.Path, $utf8NoBom)
    if (-not $re.IsMatch($content)) {
        throw "Version pattern not found in $($t.Path)"
    }
    $updated = $re.Replace($content, ($t.Replacement -f $Version), 1)
    [System.IO.File]::WriteAllText($t.Path, $updated, $utf8NoBom)
    Write-Host "  Updated: $($t.Path)"
}

# --- Android tauri.properties (optional, autogenerated by Tauri CLI) ---
$tauriPropertiesPath = Join-Path $RepoRoot "src-tauri\gen\android\app\tauri.properties"
if (Test-Path $tauriPropertiesPath) {
    $parts = $Version.Split(".")
    $versionCode = [int]$parts[0] * 1000000 + [int]$parts[1] * 1000 + [int]$parts[2]

    $content = [System.IO.File]::ReadAllText($tauriPropertiesPath, $utf8NoBom)
    $updated = [regex]::new('(?m)^tauri\.android\.versionName=.*$').Replace($content, "tauri.android.versionName=$Version", 1)
    $updated = [regex]::new('(?m)^tauri\.android\.versionCode=.*$').Replace($updated, "tauri.android.versionCode=$versionCode", 1)
    if ($updated -cne $content) {
        [System.IO.File]::WriteAllText($tauriPropertiesPath, $updated, $utf8NoBom)
        Write-Host "  Updated: $tauriPropertiesPath (versionName=$Version, versionCode=$versionCode)"
    }
}

Write-Host "App version synced to $Version" -ForegroundColor Green
